import random
from scipy.integrate import cumulative_trapezoid
from KDEpy import FFTKDE
import CAPEX


"""Number of decimals for rounding the system revenue"""
MC_decimal = {2030: 2, '2040_base': 1, '2040_SAF': 1, '2050_base': 1, '2050_SAF': 1}

"""Projected price of CO2 in $/t for 2030-2050"""
CO2_price = {2030: 69.3, '2040_base': 107, '2040_SAF': 107, '2050_base': 160, '2050_SAF': 160}

"""Internal production/consumption values of energy carriers in each pathway"""
# Internal production of power (MW), CO2 avoided (kgCO2/GJ), and green H2 consumption (GJ)
power_CO2avoided = {2030: {'BtL_FT_CCS': {'Electricity': -11.34, 'CO2avoided': 3.32+26.7, 'GreenH2': 0},
                                        'PtL_CCS': {'Electricity': 33.5, 'CO2avoided': 4.17+10.48, 'GreenH2': 0}},
                                 '2040_base': {'BtL_FT_CCS': {'Electricity': -11.34, 'CO2avoided': 2.2+26.7, 'GreenH2': 0},
                                               'PtL_CCS': {'Electricity': 100.9, 'CO2avoided': 8.43+10.48, 'GreenH2': 0},
                                               'HEFA': {'Electricity': -1.17, 'CO2avoided': 0.774, 'GreenH2': -60.12},
                                               'AtJ_starch': {'Electricity': -0.82, 'CO2avoided': 0.15, 'GreenH2': -6.16},
                                               'GtL_ATR_CCS': {'Electricity': -39.72, 'CO2avoided': -3.4+46, 'GreenH2': 0}},
                                 '2040_SAF': {'BtL_FT_CCS': {'Electricity': -11.34, 'CO2avoided': 2.2+26.7, 'GreenH2': 0},
                                              'PtL_CCS': {'Electricity': 273.15, 'CO2avoided': 22.8+10.48, 'GreenH2': 0}},
                                 '2050_base': {'BtL_FT_CCS': {'Electricity': -11.34, 'CO2avoided': 1.66+26.7, 'GreenH2': 0},
                                               'PtL_CCS': {'Electricity': 100.9, 'CO2avoided': 6.38+10.48, 'GreenH2': 0},
                                               'HEFA': {'Electricity': -1.17, 'CO2avoided': 0.59, 'GreenH2': -60.12},
                                               'AtJ_starch': {'Electricity': -0.82, 'CO2avoided': 0.12, 'GreenH2': -6.16},
                                               'GtL_ATR_CCS': {'Electricity': -169.8, 'CO2avoided': -11+46, 'GreenH2': 0}},
                                 '2050_SAF': {'BtL_FT_CCS': {'Electricity': -11.34, 'CO2avoided': 1.66+26.7, 'GreenH2': 0},
                                               'PtL_CCS': {'Electricity': 424.5, 'CO2avoided': 53.3+10.48, 'GreenH2': 0},
                                               'HEFA': {'Electricity': -1.17, 'CO2avoided': 0.59, 'GreenH2': -60.12},
                                               'AtJ_starch': {'Electricity': -0.82, 'CO2avoided': 0.12, 'GreenH2': -6.16}}}

"Price of revenue generated"
revenue_price = {'Oxygen': [110, 89.4, 96, 93, 110, 140, 165],
                              'Electricity': [55.08, 88.2, 59.8, 56.9, 45, 87.12, 64.8, 79.9, 46.08],
                              'GreenH2': [38.9, 18.3, 116.7, 50, 100, 25.6, 77.8, 26.7, 64.2, 45.8],
                              'Liquid Fuels': [23.23, 63, 46, 33.5, 28.8, 67, 82.1, 56.4, 79.3, 53.7, 72.6]}        # Oxygen in $/t, power in $/MWh, greenH2 in $/GJ, and liquid products in $/GJ




class KDE:

    def __init__(self, kernel: str, bandwidth: (str, int), sample_size: int, year: int, mode_MFSP: int):

        self.kernel = kernel
        self.bandwidth = bandwidth
        self.sample_size = sample_size
        self.year = year
        self.mode_MFSP = mode_MFSP
        self.capex_import = CAPEX.KDE(kernel='gaussian', bandwidth='ISJ', sample_size=2, year=self.year)
        self.cap_individual = CAPEX.cap_individual[self.year]              # Production capacity of each tech in GJ

        self.dataP_revenue_million = {}         # The revenue generated by each process in M$/y
        for i, j in power_CO2avoided[self.year].items():
            self.dataP_revenue_million.setdefault(i, {})
            self.dataP_revenue_million[i].setdefault('CO2avoided', self.cap_individual[i] * 8000
                                                     * j['CO2avoided'] * CO2_price[self.year] / (1e3 * 1e6))
            for m, n in revenue_price.items():
                if m == 'Oxygen' and i == 'PtL_CCS':
                    self.dataP_revenue_million[i].setdefault(m, [])
                    for p in n:
                        self.dataP_revenue_million[i][m].append(p * self.cap_individual['PtL_CCS'] *
                                                                12 * 8 * 8000 / (1000 * 1e6))
                elif m == 'Electricity':
                    self.dataP_revenue_million[i].setdefault(m, [])
                    for p in n:
                        self.dataP_revenue_million[i][m].append(p * j[m] * 8000 / 1e6)
                elif m == 'GreenH2':
                    if j['GreenH2'] == 0:
                        continue
                    else:
                        self.dataP_revenue_million[i].setdefault(m, [])
                        for p in n:
                            self.dataP_revenue_million[i][m].append(p * j[m] * 8000 / 1e6)
                elif m == 'Liquid Fuels' and self.mode_MFSP == 0:
                    self.dataP_revenue_million[i].setdefault(m, [])
                    for p in n:
                        self.dataP_revenue_million[i][m].append(p * self.cap_individual[i] * 8000 / 1e6)


        self.dataP_revenue_transform = {}
        for i, j in self.dataP_revenue_million.items():
            self.dataP_revenue_transform.setdefault(i, {})
            for m, n in j.items():
                if m != 'CO2avoided':
                    self.dataP_revenue_transform[i].setdefault(m, [])
                    for p in n:
                        self.dataP_revenue_transform[i][m].append((p - min(n)) / (max(n) - min(n)))




    def kde_estimation(self):
        """Finding the range of PDF and CDF values for the revenue generated by each pathway"""

        kde_revenue = {}
        for m, n in self.dataP_revenue_transform.items():
            kde_revenue.setdefault(m, {})
            for p, q in n.items():
                kde_revenue[m].setdefault(p, [])
                x_kde, y_kde = FFTKDE(kernel=self.kernel, bw=self.bandwidth).fit(q).evaluate()
                x = []
                for a in x_kde:
                    x.append(a * (max(self.dataP_revenue_million[m][p]) - min(self.dataP_revenue_million[m][p])) +
                             min(self.dataP_revenue_million[m][p]))
                y = []
                for f in y_kde:
                    y.append(f / (max(self.dataP_revenue_million[m][p]) - min(self.dataP_revenue_million[m][p])))
                kde_revenue[m][p].append(x)
                kde_revenue[m][p].append(y)

        kde_cdf_revenue = {}
        for i, j in kde_revenue.items():
            kde_cdf_revenue.setdefault(i, {})
            for p, q in j.items():
                kde_cdf_revenue[i].setdefault(p, [])
                kde_cdf_revenue[i][p].append(q[0])
                cdf = cumulative_trapezoid(q[-1], q[0], initial=0)
                cdf /= cdf[-1]
                kde_cdf_revenue[i][p].append(cdf)


        return [kde_revenue, kde_cdf_revenue]




    def kde_Monte_Carlo(self):

        kde_cdf_revenue = self.kde_estimation()

        """Implementing Monte Carlo simulation to obtain the distribution of the system revenue in B$"""
        decimal_NO = {2030: {'BtL_FT_CCS': 3, 'PtL_CCS': 1},
                      '2040_base': {'BtL_FT_CCS': 3, 'PtL_CCS': 0, 'HEFA': 2, 'AtJ_starch': 2, 'GtL_ATR_CCS': 2},
                      '2040_SAF': {'BtL_FT_CCS': 3, 'PtL_CCS': 0},
                      '2050_base': {'BtL_FT_CCS': 3, 'PtL_CCS': 0, 'HEFA': 2, 'AtJ_starch': 2, 'GtL_ATR_CCS': 1},
                      '2050_SAF': {'BtL_FT_CCS': 3, 'PtL_CCS': 0, 'HEFA': 2, 'AtJ_starch': 2}}
        revenue_total = []
        revenue_individual = {}
        for i in range(0, self.sample_size):
            revenue_total_temp = 0
            for m, n in kde_cdf_revenue[-1].items():
                revenue_individual.setdefault(m, [])
                revenue_individual_temp = 0
                revenue_individual_temp += self.dataP_revenue_million[m]['CO2avoided']
                for p, q in n.items():
                    random_CDF = random.uniform(0, 1)
                    for j, k in enumerate(q[-1]):
                        if round(random_CDF, 2) == round(k, 2):
                            revenue_individual_temp += kde_cdf_revenue[0][m][p][0][j]
                            break
                revenue_total_temp += revenue_individual_temp
                if self.mode_MFSP == 0:
                    revenue_individual[m].append(round(revenue_individual_temp, 0))
                else:
                    revenue_individual[m].append(round(revenue_individual_temp, decimal_NO[self.year][m]))

            revenue_total.append(round(revenue_total_temp / 1e3, MC_decimal[self.year]))



        """Frequency distribution of the system revenue (histogram)"""
        revenue_total_frequency = {}
        for h in revenue_total:
            revenue_total_frequency.setdefault(h, revenue_total.count(h))
        revenue_total_frequency_sorted = dict(sorted(revenue_total_frequency.items()))

        revenue_individual_frequency = {}
        revenue_individual_frequency_sorted = {}
        for i, j in revenue_individual.items():
            revenue_individual_frequency.setdefault(i, {})
            for p in j:
                revenue_individual_frequency[i].setdefault(p, revenue_individual[i].count(p))
            revenue_individual_frequency_sorted.setdefault(i, dict(sorted(revenue_individual_frequency[i].items())))


        """Relative frequency distribution of the system revenue (Relative histogram)"""
        revenue_total_relative_frequency = {}
        for a, b in revenue_total_frequency_sorted.items():
            revenue_total_relative_frequency.setdefault(a, b / self.sample_size)

        revenue_individual_relative_frequency = {}
        for i, j in revenue_individual_frequency_sorted.items():
            revenue_individual_relative_frequency.setdefault(i, {})
            for a, b in j.items():
                revenue_individual_relative_frequency[i].setdefault(a, b / self.sample_size)


        """Empirical PDF of the system revenue"""
        revenue_total_PDF = {}
        for c, d in revenue_total_relative_frequency.items():
            revenue_total_PDF.setdefault(c, d * 1.1 / ((max(revenue_total) - min(revenue_total)) /
                                               len(list(revenue_total_frequency_sorted.keys()))))

        revenue_individual_PDF = {}
        for i, j in revenue_individual_relative_frequency.items():
            revenue_individual_PDF.setdefault(i, {})
            for c, d in j.items():
                revenue_individual_PDF[i].setdefault(c, d * 1.1 / ((max(revenue_individual[i]) - min(revenue_individual[i])) /
                                                       len(list(revenue_individual_frequency_sorted[i].keys()))))


        """Empirical CDF of the system revenue"""
        revenue_total_CDF = {}
        for e, f in revenue_total_frequency_sorted.items():
            feedstock_total_CDF_values = list(revenue_total_CDF.values())
            counter3 = len(feedstock_total_CDF_values)
            if counter3 == 0:
                revenue_total_CDF.setdefault(e, f / self.sample_size)
            else:
                revenue_total_CDF.setdefault(e, f / self.sample_size + feedstock_total_CDF_values[counter3 - 1])

        revenue_individual_CDF = {}
        for i, j in revenue_individual_frequency_sorted.items():
            revenue_individual_CDF.setdefault(i, {})
            for e, f in j.items():
                feedstock_individual_CDF_values = list(revenue_individual_CDF[i].values())
                counter3 = len(feedstock_individual_CDF_values)
                if counter3 == 0:
                    revenue_individual_CDF[i].setdefault(e, f / self.sample_size)
                else:
                    revenue_individual_CDF[i].setdefault(e, f / self.sample_size + feedstock_individual_CDF_values[counter3 - 1])



        return [revenue_total_PDF, revenue_total_CDF, revenue_individual_PDF, revenue_individual_CDF]

